package yueyang.vostok.http.exception;

public enum VKHttpErrorCode {
    INVALID_ARGUMENT,
    CONFIG_ERROR,
    STATE_ERROR,
    NETWORK_ERROR,
    CONNECT_TIMEOUT,
    READ_TIMEOUT,
    TOTAL_TIMEOUT,
    TIMEOUT,
    RATE_LIMITED,
    BULKHEAD_REJECTED,
    CIRCUIT_OPEN,
    HTTP_STATUS,
    RESPONSE_TOO_LARGE,
    SERIALIZATION_ERROR
}
