package yueyang.vostok.game;

public record VKGameMetrics(
        boolean started,
        int roomCount,
        int logicCount,
        int pendingMatchRequests,
        long tickCount,
        long tickTimeouts,
        long tickTimeoutRoomSkips,
        long maxTickCostMs,
        long roomCreated,
        long roomClosed,
        long roomDraining,
        long roomDrainRequests,
        long roomClosedByIdle,
        long roomClosedByEmpty,
        long roomClosedByLifetime,
        long roomClosedByDrainTimeout,
        long playerJoined,
        long playerLeft,
        long playerDisconnected,
        long playerReconnected,
        long playerSessionExpired,
        long commandsReceived,
        long commandsProcessed,
        long commandsDropped,
        long commandsRejected,
        long commandsRejectedRateLimit,
        long commandsRejectedSeq,
        long commandsRejectedTimeSkew,
        long commandsRejectedPlayerMissing,
        long commandsRejectedPlayerOffline,
        long matchEnqueued,
        long matchCancelled,
        long matchSucceeded,
        long matchNotified,
        long matchAcked,
        long matchResultExpired,
        long messagesPublished,
        long messagesPushed,
        long messagesAcked,
        long messagesExpired,
        long shardImbalanceEvents,
        long shardMigrations,
        long roomClosedByLogicError,
        // 帧同步指标
        long frameSyncFramesBroadcast,   // 成功广播的帧总数（含写入历史缓冲区的帧）
        long frameSyncBroadcastErrors    // notifier 回调抛出异常的次数
) {
}
